language: java
os: linux
dist: xenial
services: haveged

git:
  depth: 1
  quiet: true

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

before_install:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh

install:
  - true

before_script:
  - ./gradlew -vq

script:
  - ./gradlew jar

matrix:
  include:
    - name: 'openjdk8'
      jdk: openjdk8
    - name: 'openjdk11'
      jdk: openjdk11
    - name: 'openjdk12'
      jdk: openjdk12

    - name: '1.8.0_112-b16'
      os: macos
      osx_image: xcode9.3
    - name: '11.0.1+13'
      os: macos
      osx_image: xcode10.1
    - name: '12+33'
      os: macos
      osx_image: xcode10.2

    # - name: 'openjdk11-hotspot'
    #   install: . install-jdk.sh --url 'https://api.adoptopenjdk.net/v2/binary/releases/openjdk11?openjdk_impl=hotspot&os=linux&arch=x64&release=latest&heap_size=normal&type=jdk'
    # - name: 'openjdk11-openJ9'
    #   install: . install-jdk.sh --url 'https://api.adoptopenjdk.net/v2/binary/releases/openjdk11?openjdk_impl=openj9&os=linux&arch=x64&release=latest&heap_size=normal&type=jdk'

    # - name: 'zulu-jdk11+29'
    #   install: . install-jdk.sh --url https://cdn.azul.com/zulu/bin/zulu11.29.11-ca-jdk11.0.2-linux_x64.tar.gz
    # - name: 'graalvm-ce-1.0.0-rc15'
    #   install: . install-jdk.sh --url https://github.com/oracle/graal/releases/download/vm-1.0.0-rc15/graalvm-ce-1.0.0-rc15-linux-amd64.tar.gz
    # - name: 'shenandoah-jdk11'
    #   install: . install-jdk.sh --url https://builds.shipilev.net/openjdk-shenandoah-jdk11/openjdk-shenandoah-jdk11-latest-linux-x86_64-release.tar.xz
    # - name: 'amazon-corretto-jdk11+9'
    #   install: . install-jdk.sh --url https://d3pxv6yz143wms.cloudfront.net/11.0.2.9.3/amazon-corretto-11.0.2.9.3-linux-x64.tar.gz


env:
  global:
    - GRADLE_OPTS="-Dorg.gradle.caching=false -Dorg.gradle.internal.launcher.welcomeMessageEnabled=false"
    - AWS_ACCESS_KEY_ID="AKIAJQUIQIL3XTBHT3DA"
    - secure: "C5Y0miWN35KMpWNT/r3n31J/JjUJA6a9I/w5DUkm5xFLv1oStOvNL9KykRQIL4+9yW7hYUcGOI0iP9ZjtbxRouP5//PCjhlgzIGJ3WImVZq4fLNl3sq3DYtgZJT5rUeXn8r8cKE3/sloEbcbz7dFNXmbSACuaZ0/T3IZpgP/Yrs="

before_deploy:
  - pip install --user awscli
  - ./gradlew copyRuntimeLibs javadoc

deploy:
  - provider: script
    script: ~/.local/bin/aws s3 sync --region=us-east-1 --cache-control "public, max-age=86400" --content-encoding utf-8 --delete build/docs/javadoc/ s3://website-javadoc.freenetproject.org
    skip_cleanup: true
    on:
      branch: next
      jdk: openjdk8
  - provider: script
    script: ./gradlew -x test publish
    skip_cleanup: true
    on:
      tags: true
      jdk: openjdk8
  - provider: releases
    skip_cleanup: true
    api_key:
      - secure: "CDYRFrmkAOdn4QJVww6/pziDVdZ67fvRsLOKbilao/oRdP0uvsYS+OfX+Spu/Y0qCY0xSehvqgUoD8KoFqWuhos3iF4N515S5WNuiqOao7Ac2vBCt0ZMJy7MktyE5mYOD1Paf891n6Z+eILWGI54GGEau3JPes0G9jdMphW4ma8="
    prerelease: true
    file: build/output/*.jar
    file_glob: true
    on:
      tags: true
      jdk: openjdk8
